name: FW CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Packages
      run: sudo apt update && sudo apt install gcc-aarch64-linux-gnu
    - name: Build FW (ARM64)
      run: cd src && cd arm64 && make -f ci.make all